global using Microsoft.AspNetCore.Authorization;
global using Microsoft.OpenApi.Models;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using Microsoft.EntityFrameworkCore;
global using System.Xml.Serialization;
global using System.Text;
global using WebApplication1.Model.Entity;
global using Microsoft.AspNetCore.Cryptography.KeyDerivation;
global using System.Security.Cryptography;
global using WebApplication1.Services;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using System.Globalization;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using DataType = System.ComponentModel.DataAnnotations.DataType;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Migrations;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using Swashbuckle.AspNetCore.Annotations;
global using WebApplication1.Data;
global using WebApplication1.Model.Interfaces;

