// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

#nullable disable

namespace WebApplication1.Data.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250515092928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Валюта", b =>
                {
                    b.Property<int>("Id_валюты")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_валюты"));

                    b.Property<string>("Название_валюты")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_валюты");

                    b.ToTable("Валюты");
                });

            modelBuilder.Entity("WebApplication1.Курсы_валют", b =>
                {
                    b.Property<int>("ID_курса")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_курса"));

                    b.Property<int>("ID_валюты")
                        .HasColumnType("int");

                    b.Property<DateTime>("Дата")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Значение")
                        .HasColumnType("decimal(15, 6)");

                    b.HasKey("ID_курса");

                    b.HasIndex("ID_валюты");

                    b.HasIndex("Дата", "ID_валюты")
                        .IsUnique();

                    b.ToTable("КурсыВалют");
                });

            modelBuilder.Entity("WebApplication1.Курсы_валют", b =>
                {
                    b.HasOne("WebApplication1.Валюта", "Валюта")
                        .WithMany()
                        .HasForeignKey("ID_валюты")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Валюта");
                });
#pragma warning restore 612, 618
        }
    }
}
